#pragma once

#include "resource.h"

#define FRACTAL_HEIGHT	256
#define FRACTAL_WIDTH	256

#define JULIA_WIDTH 1024
#define JULIA_HEIGHT 1024
#define JULIA_TOP 50
#define JULIA_LEFT FRACTAL_WIDTH

#define MAX_THREADS 4
#define JULIA_THREADS 4

#define POINTS_CONCURRENT_AVX64	4
#define POINTS_CONCURRENT_AVX32	8
#define POINTS_CONCURRENT_SSE	4
#define POINTS_CONCURRENT_SSE2	2
#define POINTS_CONCURRENT_X87	1
