#pragma once

#include "resource.h"

#define FRACTAL_HEIGHT_DEFAULT	256
#define FRACTAL_WIDTH_DEFAULT	256

#define JULIA_WIDTH_DEFAULT 1024
#define JULIA_HEIGHT_DEFAULT 1024
#define JULIA_TOP 0 // 50
#define JULIA_LEFT FRACTAL_WIDTH

#define MAX_MAND_THREADS 4
#define MAX_JULIA_THREADS 4

#define POINTS_CONCURRENT_AVX64	4
#define POINTS_CONCURRENT_AVX32	8
#define POINTS_CONCURRENT_SSE	4
#define POINTS_CONCURRENT_SSE2	2
#define POINTS_CONCURRENT_X87	1

#define MAXIMUM_MAND_SSE 4.0f


